### ISSUE TITLE
Add Database to New Connection

### ISSUE THREAD

**Issue by imperez** [fabianfiorotto/quick-query#1]
First off, I have to say this is a great package so thanks for your work on it already.

My feature request is when creating a new connection can you add an optional field for database. This can be used running a query if one isn't specified in the SQL.

**Comment by fabianfiorotto** [comment]
Check out the new release. I've added an option to contextual menu that allows you to select the default database.

**Comment by imperez** [comment]
Awesome that feature works perfectly. Thanks!
