### ISSUE TITLE
Sugestion Sqlite3 Support

### ISSUE THREAD

**Issue by obelich** [fabianfiorotto/quick-query#11]
Hiyas the most of time Sqlite are the db basic to start the proyects my sugestion is can add sqlite support please :)

**Comment by nournia** [comment]
:+1:

**Comment by fabianfiorotto** [comment]
I'm experimenting with this https://atom.io/packages/quick-query-sqlite 
Can you help me to test?

**Comment by obelich** [comment]
Sure let me install and test it :)

**Comment by obelich** [comment]
I try to connect to Sqlite but it tell me user and password i click in connect and send me the error referenceError: fs is not defined

**Comment by fabianfiorotto** [comment]
I published a new version that fixes the problem with fs. Thanks!! And  I should hide the user and password inputs but ignore them for now.

**Comment by obelich** [comment]
ok in autosave work good but in no autosave option give the same error at try to add database

**Comment by fabianfiorotto** [comment]
I'm going to close this issue. Future issues related with sqlite should be published in its repository
