### ISSUE TITLE
Items in Browser Sould be Sorted

### ISSUE THREAD

**Issue by linuxfranz** [fabianfiorotto/quick-query#15]
The items in the browser (connections, tables, columns...) are not sorted alphabetically.

It would be very useful if they were sorted or there would be an entry in the context menu for sorting them.

**Comment by linuxfranz** [comment]
I have fixed it with these changes to quick-query-browser-view.coffee:

New method:

```
  compare: (a,b) ->
    if (a.name < b.name)
      -1
    else if (a.name > b.name)
      1
    else
      0

```
And in the method @showItems:

    childrenItems = childrenItems.sort(@compare) // insert this new line
    for childItem in childrenItems
      $li = $('<li/>').addClass('entry')
      ....

Works for me.

**Comment by fabianfiorotto** [comment]
I'm not sure about sorting columns. In some systems the column order has a special meaning.
