### ISSUE TITLE
Get changes SQL doesn't work

### ISSUE THREAD

**Issue by xkraty** [fabianfiorotto/quick-query#17]
I'm on version 0.7.1 using a postgres connection and the get changes SQL button doesn't work anymore, it doesn't generate the query in the textarea above

**Comment by fabianfiorotto** [comment]
Make sure that all the primary keys are present in the select statement

**Comment by xkraty** [comment]
I made few tests and look like the issue is when the table has a foreign key

**Comment by fabianfiorotto** [comment]
I [fixed](https://github.com/fabianfiorotto/quick-query/commit/12838eb808e12f2da2d59e32275e8a832c971faa) a bug with foreigns keys. Try again, maybe this solves your problem.

**Comment by xkraty** [comment]
Awesome!
