### ISSUE TITLE
Query Result - Button for "Apply changes" after doing some row modification

### ISSUE THREAD

**Issue by nahuelhds** [fabianfiorotto/quick-query#20]
It could be nice if we can directly apply the changes we made through a button and by copying the SQL with "Copy changes' SQL" and a new tab that we have to run.

We would reduce the number of steps (3 or 4) with a simple button for it.

**Comment by fabianfiorotto** [comment]
Run the sentences manually works like a prompt dialog. That avoids to make mistakes. Only readonly sentences run in background in this package.

**Comment by nahuelhds** [comment]
That why I say to use a button. Not applyng then until we click that button.

I'm basing this feature request in the robust MySQL Workbench which I use a lot.
I like this package because is lightweight.
So, in my day use this for little changes and MySQL Workbench for more advances requirements

**Comment by BusfyJan** [comment]
:+1:

**Comment by fabianfiorotto** [comment]
I added a button to apply the changes with a confirmation stage. The accept button is in the same place than the edit button, so you can apply the changes with a double-click. Also, with the new cursor, you can apply the changes pressing <kbd>ctrl</kbd> + <kbd>s</kbd> and then <kbd>enter</kbd>. I've reduced the number of steps as much as I could.
