### ISSUE TITLE
Allow closing the query overlay more easily.

### ISSUE THREAD

**Issue by Gert-dev** [fabianfiorotto/quick-query#22]
Hello

Whenever you execute an INSERT or UPDATE statement, an overlay will be shown with a message such as "1 row(s) affected". It seems this overlay can only be closed by clicking the (small) banner or pressing the escape key. Would it be possible to allow closing it by clicking the darkened overlay around it as well?

Another interesting possibility would be to show a (persistent or not) atom notification with the result in it, which is less disruptive to the workflow than the entire Atom window being hijacked ;-).

Thanks in advance

**Comment by fabianfiorotto** [comment]
That dark overlay is only available in certain themes. I use "Atom light" and I can write in the editor while a dialog is open. 

When I wrote that code I didn't know about atom notifications. I'm going to take a look on this.

**Comment by Gert-dev** [comment]
Thanks.

In case you decide to stick with the overlays: is it possible that the displaying of the overlay or popup is not debounced? When performing a SELECT query on a local database, my screen sometimes flickers momentarily. I think this is because the popup is showing to indicate that the results are being fetched, but it completes so quickly that the overlay immediately hides again. An alternative to the "In progress" popup would perhaps be to use Atom's loading-spinner (see also the styleguide) that could be shown inside the results pane whilst the results are being fetched.

**Comment by fabianfiorotto** [comment]
Atom notifications are pretty annoying, cover the browser's buttons and don't disappear when you click on them. I don't know what I'm going to do with this.
![atom notifications](https://cloud.githubusercontent.com/assets/898842/15686431/b2d03128-2746-11e6-86e3-09069bfaf846.png)

**Comment by Gert-dev** [comment]
Atom notifications support the `dismissable` property that you can set to `true` to make them have a close button (you can also press the escape key then to dismiss them). Non-dismissable notifications seem to disappear by themselves after a couple of seconds. What is strange is that you (or at least I) can't seem to have both: dismissable and disappearing over time. If I do this:
```coffeescript
atom.notifications.addSuccess 'Success', {
    dismissable : true
    detail : 'Test'
}
```

... I get a notifications with a close button, but it won't disappear over time. Strangely enough, the git-plus package _does_ somehow seems to have both at the same time. Judging from the source code, however, it also seems to be using the same function on the background.

On another note: not sure if this is feasible for you, but some other options with regards to the toolbar buttons:
* For running queries you could optionally plug in to the awesome [intentions](https://github.com/steelbrain/intentions) package so you can press `ctrl-enter` or `alt-enter` in SQL code (that could work even for SQL embedded in other languages, if they highlight SQL queries, such as PHP).
* You could put the buttons on the bottom.
* You could add context menu items (after right-clicking on the pane) for adding a new connection.

**Comment by fabianfiorotto** [comment]
well... Now I'm using atom notifications to show information. But I added a little hack that allows close them with a click.
