### ISSUE TITLE
Option to show panel on start-up.

### ISSUE THREAD

**Issue by Gert-dev** [fabianfiorotto/quick-query#23]
Hello

It would be neat if the panel could be restored on start-up if it was visible (or just always visible on start-up, perhaps by toggling a preference).

Thanks in advance

**Comment by fabianfiorotto** [comment]
To restore the state of the browser I need to activate the package when atom starts and that would slow down the start up. If you want to show the browser when atom starts you could add these lines to your init script

```coffeescript
workspaceElement = atom.views.getView(atom.workspace)
atom.commands.dispatch workspaceElement, 'quick-query:toggle-browser'
```

**Comment by Gert-dev** [comment]
That's sufficient for me, thanks :+1:
