### ISSUE TITLE
Dependency on git.less which does not exist in all themes

### ISSUE THREAD

**Issue by joebuckingham** [fabianfiorotto/quick-query#26]
**DBMS I'm using:**  Postgres
**OS I'm using:**   OS X 10.11.6
**Theme I'm using:** Seti UI
**Atom version:**  1.10.2

`styles/quick-query.less` tries to import `git.less`, which doesn't exist in all UI themes. Currently this stops the LESS from compiling when using those themes, which breaks some of the layout rendering. 

Would be great to include a fallback where `git.less` can't be found, though it's obviously not a huge priority as it's simple enough to just use a theme that has the file as a workaround.

Will try and create a PR myself if I get a chance - have only just started using quick-query but I can tell it's going to be a lifesaver!

**Comment by fabianfiorotto** [comment]
I'm aware of that. But I can't check if that file exists because the "(optional)" feature is not available on atom.

**Comment by joebuckingham** [comment]
Ah, you're right. That's a pain - [looks like a fix for that is coming soon though](https://github.com/atom/less-cache/pull/8#issuecomment-242902932)! 

Thanks for getting back so quickly.

**Comment by fabianfiorotto** [comment]
Atom 1.17 will implement optional. that means that the new version of this package will drop compatibility with older versions of atom.

**Comment by fabianfiorotto** [comment]
Atom 1.17 was released today and with it comes the end to the dependency on git.less :tada: Could you test if this package is working with your theme?
