### ISSUE TITLE
Is there a way to integrate autocomplete?

### ISSUE THREAD

**Issue by hugeme** [fabianfiorotto/quick-query#29]
**DBMS I'm using:**  ((MySQL))
**OS I'm using:**   ((10.12 Sierra))
**Atom version:**  ((1.12.6))

Hello, I like your package very much. So thanks for providing it.

Is there a way to include the support for autocompletion?

**Comment by fabianfiorotto** [comment]
I released a new version with autocomplete integration. To get it working you have to select one default database and SQL has to be selected as the editor's syntax language. Maybe the suggestions' order could be improved a little to show relevant suggestions first.

**Comment by hugeme** [comment]
@fabianfiorotto Thank you for doing that so quickly!! 

I apologize for the triviality of my question. But how do you:

"select one default database and SQL has to be selected as the editor's syntax language"

Thank you in advance for elaborating on that question!

**Comment by fabianfiorotto** [comment]
To select a default database: In the browser right click on the database icon then in the context menu click "Set as default". The default database is shown with bold font.

To select SQL syntax. In the bottom right corner click on the syntax name. In a blank page it's "plain text". A fuzzy finder will appear. Type SQL and press enter.
