### ISSUE TITLE
Add a "rows affected" or "rows returned" item to the status bar

### ISSUE THREAD

**Issue by mika76** [fabianfiorotto/quick-query#30]
**DBMS I'm using:**  Mysql
**OS I'm using:**   Win 10
**Theme I'm using:** One Dark
**Atom version:**  1.12.7

**Comment by fabianfiorotto** [comment]
I released a new version with a row count in the status bar. Also you can toggle the result view from the status bar.

**Comment by mika76** [comment]
Works great - thanks!
