### ISSUE TITLE
Expanding the autocomplete integration.

### ISSUE THREAD

**Issue by hugeme** [fabianfiorotto/quick-query#32]
**DBMS I'm using:**  ((MySQL))
**OS I'm using:**   ((10.12.3))
**Atom version:**  ((1.13.1))

Hello @fabianfiorotto, thank you for putting all that work in this nice package!

Previously, due to some request you were able to integrate that cool feature. 
https://github.com/fabianfiorotto/quick-query/issues/29

However, there are still some things not really clear for me. (Sorry in advance for that long illustration):

Example: 
Having two schemas A and B 

Schema A has tables C and D with  C.ID, C.Age and D.ID, D.gender
Schema B has tables F and G with F.ID, F.income and G.ID, G.attitude

I would expect the following (at least by using some popular clients):

    SELECT
              *
     FROM A.D d   -- After putting A. alphabetical listing of C and D appears initially.
     INNER JOIN B.F f ON f.ID = d.ID -- After putting B. alphabetical listing of F and G appears initially.
                                                           -- After putting f. alphabetical listing of ID and Income appears initially and so on.

Working with the current state of autocompletion:

      SELECT
              *
      FROM A.D d     --After putting A. no listing appears so one has to know all tables ex ante
      INNER JOIN B.F f ON f.ID = d.ID  --After putting B. no listing appears. After typing, tables from A are suggested somehow..

It would be so cool if quick- query could integrate the upper behavior.

Thank you

Eugene

**Comment by fabianfiorotto** [comment]
I am not showing suggestion for others databases. First because I thought that those suggestions weren't useful and second because crossing databases is not allowed in postgres and I thought that it could cause some troubles to postgres users. I'll add those suggestions in a future version only for users who don't use postgres.

**Comment by hugeme** [comment]
@fabianfiorotto You are completely right. I just pointed out the problem incorrectly. I was referring with A and B as an example of multiple schemas rather then databases. sorry for that. I updated the question.

**Comment by fabianfiorotto** [comment]
Please try again. You will get suggestion from others databases now.

**Comment by hugeme** [comment]
Hello @fabianfiorotto , sorry for my late reply.

Thank you again for hat adjustment. Now Im able to join tables from different schemas almost without any problems using your enhancement. One thing is still sometimes uncomfortable. When accessing tables or columns: 
JOIN B.F f ON f.ID = d.ID 
the tables or columns dont pop up automatically in alphabetical order. Frequently that results in looking up the column names in the Browser before doing joins etc.

**Comment by fabianfiorotto** [comment]
If the list is too long you can continue typing to filter the suggestions . If your tables have a prefix you can type the table's name without the prefix and the autocomplete will fix it. For instance, I work a lot with drupal and most drupal tables start with field_data_field_something. I just put the field name and the autocomplete fill the rest.
