### ISSUE TITLE
Dropping a database doesn't remove it from the browser

### ISSUE THREAD

**Issue by zer0tonin** [fabianfiorotto/quick-query#35]
**DBMS I'm using:**  MySQL
**OS I'm using:**   Ubuntu 16.10
**Theme I'm using:** default
**Atom version:**  Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

After doing a database drop, the browser should refresh to make it disappear from it. Instead right now we just get the error message "Quit inactivity timeout " (even if the drop was successful).

**Comment by fabianfiorotto** [comment]
I put that timeout there because with high latency connection the browser went crazy. I think is time to cache the browser and increase that timeout.

**Comment by fabianfiorotto** [comment]
I changed the timeout to 40 seconds. That should be enough to complete a drop.
