### ISSUE TITLE
Object.require is deprecated.

### ISSUE THREAD

**Issue by dcaruelle** [fabianfiorotto/quick-query#36]
Use `remote.Dialog` instead of `remote.require("dialog")`
```
Object.require (/Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:57:12)
HTMLButtonElement.<anonymous> (/Users/dcaruelle/.atom/packages/quick-query/lib/quick-query-connect-view.coffee:88:27)
HTMLButtonElement.dispatch (/Users/dcaruelle/.atom/packages/quick-query/node_modules/jquery/dist/jquery.js:4435:9)
HTMLButtonElement.elemData.handle (/Users/dcaruelle/.atom/packages/quick-query/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by fabianfiorotto** [comment]
What version are you using? I don't get any warning in 1.15

**Comment by DamianK** [comment]
Fabian, I have v. 0.9.2 and this line dialog = remote.Dialog || remote.require('dialog') || remote.require('electron').dialog and in Atom 1.16 I still get the deprecation error.

**Comment by DamianK** [comment]
Fabian, I discovered that the error occurs when installing from apm. If I install directly from github, then the error is gone. So the fix works, only not from the install from apm. 
Regards,
Damian

**Comment by fabianfiorotto** [comment]
Probably you forgot to restart atom.
