### ISSUE TITLE
An easy way to reconnect

### ISSUE THREAD

**Issue by hugeme** [fabianfiorotto/quick-query#37]
DBMS I'm using: ((MySQL,Postgresql))
OS I'm using: ((10.12.3))
Atom version: ((1.15.0))

Hello @fabianfiorotto , thanks again for your cool package. My colleagues and me are more and more relying on atom in our day to day business. For the database query part we are relying on quick query where we  almost hourly query multiple connections (mysql & postgresql)

In that regard, we four experience the same "strange" behaviour. When a query is a bit complex aka multiple joins for instance errors occur:

`Error: inactivity timeout` or `read ETIMEDOUT`
The same queries run without issues with different other clients.

Additionally, after some time we have to reopen a connection or reopen atom in order to query the existing multiple connections. 

Feel free to ask if I explained myself inaccurately.

**Comment by fabianfiorotto** [comment]
As I said in #35 I put that timeout to avoid a weird behaviour with hight latency connections. That was a quick solution and I'm going to change it soon.

Can you explain a bit more about your problem with multiple connections? Did you get some error message?

**Comment by hugeme** [comment]
Ah ok, did not see that. I think I underscored the wrong part of the second issue. Its basically not about the multiple connections per se. 
We use a local postgre, a remote mysql, and a remote postgre. So basically, everything is fine when using simple queries (otherwise #35). However, when atom is open for a while the query runs without finishing "Running query" (no error returns - checking mysql processlist or pg_stat_activity no query has been sent).  Before that, I just open a new editor or use existing editor to query one of those connections. After restarting atom everything is fine again. After some time same behavior occurs. Does that make sense?

**Comment by fabianfiorotto** [comment]
Maybe the server is configured to close inactive connections. This package is prepared to reconnect in those cases but it seems like something isn't working properly. I'll try to figure out what is going on.

Meanwhile a better workaround could be select the default database again. that should refresh the connection. But I'm not sure if that will help you because I can't reproduce your problem yet. If that doesn't work remember that you can reload atom  with the command `window:reload` (in win and linux <kbd>ctrl</kbd> + <kbd>shift</kbd>+ <kbd>F5</kbd>) you don't need to close the editor.

**Comment by hugeme** [comment]
I have already tried, when that is happening to select the specific DB as default. However, the query doesnt finish without an error here as well. Please feel free to ask me if you need more information to approach reproducibility!

**Comment by fabianfiorotto** [comment]
I added an option to reconnect. That option closes the selected connection and creates a new one with the same connection info.
