### ISSUE TITLE
I get an error when trying to install quick-query 

### ISSUE THREAD

**Issue by DimitrisM83** [fabianfiorotto/quick-query#38]
![image](https://cloud.githubusercontent.com/assets/27409938/25385326/5f0d1da6-29cc-11e7-92ba-b91bf95bcdfc.png)

**DBMS I'm using:**  ((mssql))
**OS I'm using:**   ((Windows 10))
**Theme I'm using:** ((Atom Material))
**Atom version:**  ((1.16.0))

**Comment by fabianfiorotto** [comment]
see #26
