### ISSUE TITLE
Cannot change database

### ISSUE THREAD

**Issue by pepjo** [fabianfiorotto/quick-query#39]
**DBMS I'm using:**  postgresql
**OS I'm using:**   windows 10 (1703)
**Theme I'm using:** Default
**Atom version:**  1.18

I'm trying to connect to a database using a user with no access to the "postgres" database.
When I connect I get this error:
`error: permission denied for database "postgres"`

I cannot find how to select a different database :/

**Comment by fabianfiorotto** [comment]
I could add an input to fill the default database. But probably you won't be able to browse through the databases with those restricted permissions.

**Comment by pepjo** [comment]
A simple text input would be perfect, I know the DB name, so don't really need to browse through the databases.

However, I can see the other databases names on pgAdmin, I just cannot connect to them. So, I'm guessing that I do have permission to browse through the databases names.

**Comment by fabianfiorotto** [comment]
I added a mini editor to fill the default database. It's collapsed by default. I don't want that the connect view grow too much.

**Comment by pepjo** [comment]
Thank you! Now it works perfectly! :)
