### ISSUE TITLE
JSONB not rendered properly

### ISSUE THREAD

**Issue by johngibb** [fabianfiorotto/quick-query#43]
**DBMS I'm using:**  Postgres
**OS I'm using:**   Mac
**Theme I'm using:** N/A
**Atom version:**  1.19.2

To Reproduce:

    create table example (
        data jsonb
    );

    insert into example
    values('{"key": "value"}');

    select * from example;

Result:

| # | data            |
| - | --------------- |
| 1 | [object Object] |

Expected:

| # | data             |
| - | ---------------- |
| 1 | {"key": "value"} |

**Comment by fabianfiorotto** [comment]
Fixed. thanks for reporting it.

**Comment by johngibb** [comment]
Thanks! Your fix was better than mine :)
