### ISSUE TITLE
SCROLL

### ISSUE THREAD

**Issue by 501336North** [fabianfiorotto/quick-query#45]
**DBMS I'm using:**  (PostgreSQL)
**OS I'm using:**   (OSX)
**Theme I'm using:** (default)
**Atom version:**  (1.19.2)

Great package, very useful.  Unfortunately our DB has lots of tables and we cannot access the last few tables as the panel is not scrollable.  Please add scroll feature.

**Comment by fabianfiorotto** [comment]
The browser is scrollable from the beginning. This problem could be caused due to a package incompatibility. Did you install something that changes the tree view or the docks system behavior?

**Comment by fabianfiorotto** [comment]
Also, you could try with another theme. One theme's scrolls are too thin I have problems to find them too.
