### ISSUE TITLE
MS SQL Domain Login support

### ISSUE THREAD

**Issue by mrkeysh** [fabianfiorotto/quick-query#46]
MS SQL Server
Windows 10
One Dark / Atom Dark
1.19.7

Logging in to MS SQL Server does not work when using "domain" authentication.

**Comment by fabianfiorotto** [comment]
Since SQL Server isn't free software is very hard for me to test these kinds of features. Could you help me with this? Please hardcode the domain in the constructor of the connection class on your local copy of the module and test if it connects to your server.
https://github.com/fabianfiorotto/quick-query-mssql/blob/3f7e06868bd374f702ba9fa61a31d5ea7cabd84f/lib/quick-query-mssql-connection.coffee#L82
```coffeescipt
  constructor: (@info)->
    @info.server = @info.host
    @info.database ?= "master"
    @info.domain = "your_domain_here"
```
If this works for you I'll figure out how to add the widget to fill the domain in the connection view.

**Comment by mrkeysh** [comment]
Sorry for the delayed response.
That would be awesome to help get this working for MS SQL Server.
I completely understand that MS SQL Server isn't free software and it becomes difficult to develop for that established connection.  Actually, SSMS is free and I think there is a "free" / lite version that MS offers now, but the difficulty would still be this situation, where you have a "domain" account on the MS SQL Server.  I think that would need Active Directory, which I don't think has a free version.
Actually, connecting to MS SQL Server with a local ID that is created on SQL server works great...no issues, no complaints.  Just as an FYI....so it seems specific to the domain accounts.

I tried to hardcode my domain as you suggested.  
I left the "@emitter in there and tried to remove it and neither worked.  Code Snippet below.


`  constructor: (@info)->
    @info.server = @info.host
    @info.database ?= "master"
    @info.domain = "my_domain"
    @emitter = new Emitter()`

and 
`  constructor: (@info)->
    @info.server = @info.host
    @info.database ?= "master"
    @info.domain = "my_domain"`

**Comment by fabianfiorotto** [comment]
Don't remove the emitter. I forgot to tell you that you need to restart atom each time you change the code. You can restart it pressing <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>f5</kbd>

**Comment by mrkeysh** [comment]
Thank you, that actually worked.  I closed and reopened it each time, but that didn't seem to be enough.  The ctrl + shift + f5 worked with the addition of the 
`@info.domain = "mydomain" `
...and leaving in the emitter.

However, as you know, because the domain is hardcoded, i can't add or create another connection that is not part of the domain.  My case (which is annoying), I have a domain MS SQL Server that I use a domain account to connect to it, and I have another non-domain MS SQL Server (hosted by another company) that I have to connect to and I use a 'local' ID on that SQL server.  
So this works great, but its just obnoxious for me to go back and forth between each.  Not your fault or anything, I am just venting.
Thank you again.

**Comment by fabianfiorotto** [comment]
Hey! that's great!
I'll add the widget to fill the domain son. Meanwhile, you can add a little hack to use it.
```
  constructor: (@info)->
    @info.server = @info.host
    @info.database ?= "master"
    @info.domain = "your_domain" if @info.host == "some_host"
```

**Comment by mrkeysh** [comment]
Hey there, I really don't know CoffeeScript at all and haven't developed at all for Atom.io.  I have done some JavaScript and jQuery development.  
With the code you gave me and some searches I was able to possible bring it to the next level....probably something similar to what you are going to do.

`  constructor: (@info)->
    @info.server = @info.host
    @info.database ?= "master"
    @info.domain = if (@info.user.search /\\/)>-1 then @info.user.split("\\").slice(0,1).toString() else ""
    @info.user = @info.user.split("\\").slice(-1).toString() if @info.user.search /\\/ >= 0
    @emitter = new Emitter()`

**Comment by fabianfiorotto** [comment]
I think you could achieve the same doing
```
constructor: (@info)->
    @info.server = @info.host
    @info.database ?= "master"
    [@info.domain,@info.user] = @info.user.split(/\\/) if @info.user.search(/\\/) > -1
    @emitter = new Emitter()
```
I already thought in doing something like that. I don't like the idea of adding that much options to the connect view, it could become confusing... but I don't know...

**Comment by mrkeysh** [comment]
I agree, too many options for that connection view could be too confusing.  
But based on this, we wouldn't be adding another form field for a user to enter, so it wouldn't be too confusing for user entry.  Possibly just change the title of the user field from "user" to "domain*\user (*optional domain)" or something.  For the code not to be too confusing....having 2 lines separated like what I have makes it less confusing, though I know my code is very verbose.  What you have written, combining it into 2 lines I don't think is confusing at all.  (I am slightly confused about the "IF" statement after the assignment in the same line, but that seems to be a caveat of the language that one would pick up).  This is also the only place that the domain and user would be spliced together in general.

**Comment by mrkeysh** [comment]
got the update...i am not 100% if its working or not, I am having some general issues right now with connecting to MS SQL via domain.  I will let you know, thank you!

**Comment by mrkeysh** [comment]
Corrected everything on my end for testing and it works great!  Thank you for the update!
