### ISSUE TITLE
[FEATURE REQUEST] ANSI Information Schema

### ISSUE THREAD

**Issue by PapsOu** [fabianfiorotto/quick-query#47]
**DBMS I'm using:**  PostgreSql

Is it possible that the Database Browser can show the information_schema schema in the database list ?

I think i would be usefull for PostgreSql and for MySql (I don't really know if other Dbms are following the ANSI, as of this list https://en.wikipedia.org/wiki/Information_schema#Implementation).

**Comment by fabianfiorotto** [comment]
I hid this kind of tables on purpose because I thought they might confuse some users. Maybe I could add an option in the settings to display them.

**Comment by PapsOu** [comment]
Yes an option would be very useful
