### ISSUE TITLE
columns with the same name in the same table have always the same results

### ISSUE THREAD

**Issue by FrancescoCadei** [fabianfiorotto/quick-query#50]
**DBMS I'm using:**  ((MySQL))
**OS I'm using:**   ((Ubuntu 17.04))
**Theme I'm using:** ((one-dark-ui, atom-dark))
**Atom version:**  ((1.22.1 x64))

**Comment by fabianfiorotto** [comment]
Impossible to solve this until MySQL driver implements array API. 
https://github.com/mysqljs/mysql/issues/770
https://github.com/mysqljs/mysql/pull/1637
