### ISSUE TITLE
sqlite data not refreshing after insert

### ISSUE THREAD

**Issue by si458** [fabianfiorotto/quick-query#51]
**DBMS I'm using:**  sqlite
**OS I'm using:**   OSX High Sierra 10.13.2
**Theme I'm using:** Default (One Light)
**Atom version:**  1.23.1

not sure if im being stupid or something maybe wrong
1) click 'db.sqlite' - tab opens at side fine
2) right click 'mytable' in main db then select rows - fine
3) press 'play' icon in tab and shows data underneath query - fine
4) go to my php page and insert 2 entrys into table - fine
5) press 'play' icon in tab and data still only showing 1 entry and not 3?
6) open up base app or sqlite cmd and shows 3 entrys?

it just seems to not be refreshing the data in view?

**Comment by fabianfiorotto** [comment]
SQLite databases are files. When you click on a .sqlite file this package opens that file. To see changes made by another program it would be necessary to close the file and open it again. I could reopen the file in each query but any changes made that wasn't saved would be lost. There are two possible changes that I could do to solve this:
- Reopen the file automatically for each query in autosave mode so we avoid loose data.
- Add an option to reopen the file in the context menu and the users chose when they want to refresh with a confirmation dialog telling to them that are going to lose their data.

I don't know which option is more intuitive.

As a workaround, if you want to close the file just select the connection and press <kbd>supr</kbd>

**Comment by si458** [comment]
I found if i right click the connection and close it
Then double click the sqlite file and then click run the rows are there
Other applications that I use for sqlite all have a refresh button which I press and can see the rows being added
Maybe next to the play and add button have a refresh button
And when you click the refresh button it simply closes and reopens the file and then maybe runs the query again

**Comment by fabianfiorotto** [comment]
I added an option to reconnect. That should refresh the tables.
