### ISSUE TITLE
[FEATURE REQUEST] Be able to name connections

### ISSUE THREAD

**Issue by bbova** [fabianfiorotto/quick-query#54]
I have a lot of connections on localhost just hitting different ports and the UI is very hard to tell which is which because they all have the name:
mysql://brandon.bova@127.0.0.1

It would be a great help if you could name each connection so then I can have something like prod and test, etc.

**Comment by fabianfiorotto** [comment]
Do you have a lot of MySQL instances running in different ports on the same machine? And, you use all of those instances in the same project?

**Comment by bbova** [comment]
Yeah, I setup ssh tunnels to different ports for mysql databases on a bunch of different servers.  Hence, I have a need to be able to name each connection since each is named mysql://brandon.bova@127.0.0.1 in the database tab

**Comment by fabianfiorotto** [comment]
You can assign to your host as many names as you want in your `host` file.

**Comment by bbova** [comment]
@fabianfiorotto , can you provide an example?  I do not know what you mean where I can set up names in the `hosts` file

**Comment by fabianfiorotto** [comment]
Edit your `hosts` file. In Linux it's located in `/etc/hosts` in windows `C:\Windows\System32\Drivers\etc\hosts`

Add lines at the end of the file like these
```
  127.0.0.1       dev.project1.local
  127.0.0.1       test.project1.local
  127.0.0.1       prod.project1.local
  127.0.0.1       dev.project2.local
  127.0.0.1       test.project2.local
  127.0.0.1       prod.project2.local
```
Then connect to one of those names depending on the envirnoment and you will be able to recognice them later.
