### ISSUE TITLE
ERROR while creating new

### ISSUE THREAD

**Issue by Powerhouse28** [fabianfiorotto/quick-query#59]
**DBMS I'm using:**  Mysql
Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

I am getting this type of error while doing the 1st step

**Comment by fabianfiorotto** [comment]
Please, log in using the terminal and perform the following query to know which auth method is the server expecting. Then paste the result here so we can look if the driver supports it.

```sql
SELECT host,user,plugin 
FROM mysql.user
WHERE user = 'youruser'
and host = 'yourhost'
```

**Comment by Powerhouse28** [comment]
> Please, log in using the terminal and perform the following query to know which auth method is the server expecting. Then paste the result here so we can look if the driver supports it.
> 
> ```sql
> SELECT host,user,plugin 
> FROM mysql.user
> WHERE user = 'youruser'
> and host = 'yourhost'
> ```

log in using terminal you mean in my sql command line client ?

**Comment by fabianfiorotto** [comment]
yes

**Comment by fabianfiorotto** [comment]
Have you been able to connect with another client? It's SQL you can run it wherever you want. I told you to use the command line because is less probable that you have issues trying to connect there.

**Comment by Powerhouse28** [comment]
![Capture](https://user-images.githubusercontent.com/26279434/55276759-4e0ad300-531d-11e9-8139-c046cbcaff14.PNG)



You mean like this ?

**Comment by fabianfiorotto** [comment]
Ok. Now run the query
![mysql](https://user-images.githubusercontent.com/898842/55404472-59811880-552e-11e9-98aa-23aa4b66e088.png)

**Comment by Powerhouse28** [comment]
> Ok. Now run the query
> ![mysql](https://user-images.githubusercontent.com/898842/55404472-59811880-552e-11e9-98aa-23aa4b66e088.png)

Done now what ?

**Comment by fabianfiorotto** [comment]
...paste the results here.

**Comment by Powerhouse28** [comment]
![git](https://user-images.githubusercontent.com/26279434/55666549-2c09d700-586e-11e9-8dee-c74118debad2.png)

**Comment by Powerhouse28** [comment]
![git2](https://user-images.githubusercontent.com/26279434/55666576-adfa0000-586e-11e9-8569-07a093f25e57.png)

**Comment by fabianfiorotto** [comment]
It seems like that authentication protocol isn't supported by the driver
https://github.com/mysqljs/mysql/issues/2002

And probably it won't be ready any soon. You could change your authentication protocol or use another client  :disappointed:

**Comment by Powerhouse28** [comment]
Can you suggest me another protocol or client?

**Comment by fabianfiorotto** [comment]
To change your protocol you can search for a tutorial in google there are tons of them. Here is the first result
https://medium.com/@crmcmullen/how-to-run-mysql-8-0-with-native-password-authentication-502de5bac661

If you don't want to change the protocol you could try with MySQL workbench. That is the official client for MySQL provided by Oracle. You shouldn't have problems with it.

**Comment by fabianfiorotto** [comment]
I've switched to mysql2 which does support the new protocol. it also supports stream connections and array API. So it's a win win win
