### ISSUE TITLE
Getting error when trying to install

### ISSUE THREAD

**Issue by Soryyyn** [fabianfiorotto/quick-query#60]
**OS I'm using:**   Windows 10
**Atom version:**  1.38.2
**Error:**  npm ERR! code 1

Getting this error when trying to install quick-query through apm:
> npm ERR! Command failed: C:\Program Files\Git\mingw64\bin\git.EXE submodule update -q --init --recursive
npm ERR! C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 21: .: git-sh-setup: file not found
npm ERR!

**Complete Log:**
[2019-07-09T06_26_52_545Z-debug.log](https://github.com/fabianfiorotto/quick-query/files/3371490/2019-07-09T06_26_52_545Z-debug.log)

**Comment by fabianfiorotto** [comment]
I don't use windows but according to what I've found on google you have to add `git-core` to the PATH system variable.

https://stackoverflow.com/questions/49256190/how-to-fix-git-sh-setup-file-not-found-in-windows#comment88245403_49256190

**Comment by fabianfiorotto** [comment]
Are you able to install other packages?

**Comment by Soryyyn** [comment]
I already did that before the installation. Just connected via Hotsport fixed it. Strange.

Thanks for the help!
