### ISSUE TITLE
[FEATURE REQUEST] Database browser stay enabled option.

### ISSUE THREAD

**Issue by vivi90** [fabianfiorotto/quick-query#61]
**DBMS I'm using:**  MySQL, PostgreSQL, SQLite
**OS I'm using:**   Xubuntu 18.04 LTS 64bit
**Theme I'm using:** One Dark + editor-background
**Atom version:**  1.39.1

**Comment by fabianfiorotto** [comment]
Duplicated: https://github.com/fabianfiorotto/quick-query/issues/23
