### ISSUE TITLE
Can`t find View >> Toggle Database Browser

### ISSUE THREAD

**Issue by janstieler** [fabianfiorotto/quick-query#64]
Hi,
I have activated your package but I can't find the `View >> Toggle Database Browser`. I have it not in my view-menu.

**DBMS I'm using:**  SQLite 3
**OS I'm using:**   OS X Catalina 10.15.3 (19D76) 
**Theme I'm using:** One Light
**Atom version:**  1.48.0

Thanks

**Comment by fabianfiorotto** [comment]
You can use the command palette to toggle the browser.  Press <kbd>Cmd</kbd>+ <kbd>Shift</kbd>+ <kbd>P</kbd> and type "Toggle Database Browser" and then press <kbd>enter</kbd>.

**Comment by janstieler** [comment]
Hi,
   this I have also tried but the I got the message `no matches found`.
   But the package is installed and active. I tried also to deactivate and reactivate it but nothing changed.
   
   Cheers

**Comment by fabianfiorotto** [comment]
Try searching "Quick Query: Toggle Browser" instead.

**Comment by janstieler** [comment]
Hi,
it finds nothing. And now?
Do you use it with the Atom 1.48? Eventually the Atomversion is the problem?

**Comment by fabianfiorotto** [comment]
I also use Atom 1.48.0 but my Operative System is Linux

![imagen](https://user-images.githubusercontent.com/898842/86833783-60230780-c070-11ea-947e-10ef5bc762f3.png)

**Comment by fabianfiorotto** [comment]
You can also open the developer tools with “Cmd + Option + I” and check in the console to see if there is an error.
Maybe an error in another package is blocking this one.
