### ISSUE TITLE
I NEED HELP

### ISSUE THREAD

**Issue by jguzmanv** [fabianfiorotto/quick-query#65]
error in the instalation QUICK-QUERY

![Sin título](https://user-images.githubusercontent.com/67495432/89377021-932fd980-d6b6-11ea-96c7-2d1500669c52.jpg)

WINDOWS 8.1
I HAVE MYSQL

Acabo de ver q estas en Argentina, me sale ese error cuando quise instalar ese paquete, quiero trabajar con este Editor en mi Base de Datos en MySQL

**Comment by fabianfiorotto** [comment]
Esto está relacionado con #62 
Este paquete necesita de **git** para instalarse porque estoy usando una versión personalizada del driver mysql. Eso es porque las personas que mantienen ese driver se niegan a implementar algunas cosas necesarias para este paquete.

Instrucciones de como instalar GIT en windows
https://git-scm.com/book/es/v2/Inicio---Sobre-el-Control-de-Versiones-Instalación-de-Git
