### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by rjousse18** [fabianfiorotto/quick-query#67]
Is it possible to create an option "insert" and display an interface to insert data into table like phpmyadmin or Microsoft sql management studio ?
In the package todos-show there is an example table display so i ask the question

**Comment by fabianfiorotto** [comment]
There is an option insert. Just right-click on the result table and click on "New record". I could have bugs I don't use it that often but give it a try.

**Comment by rjousse18** [comment]
Ho thanks !!
