### ISSUE TITLE
How to configure the connection?

### ISSUE THREAD

**Issue by llagerlof** [fabianfiorotto/quick-query#7]
Where is the connection configuration file?

**Comment by fabianfiorotto** [comment]
I don't understand
Do you want to edit an existing connection? 
You can delete it and create a new one.

**Comment by llagerlof** [comment]
Sorry, I asked this because I could not make this package works.
What I need to know is how to connect to my database using you plugin. How do your package will know my server IP, user and password to connect? Which are the shortcuts? 
Thanks.

**Comment by fabianfiorotto** [comment]
There are two ways to add a new connection.
1- With the command: Open the command palette (<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>P</kbd>) and type "Quick query New Connection"
2- From the browser: Open the browser with <kbd>alt</kbd>+<kbd>\\</kbd> and click the plus (+) icon

**Comment by llagerlof** [comment]
Nice. It worked perfectly.
Any plans to add support for Oracle?

Thanks.

**Comment by llagerlof** [comment]
Nice. It worked perfectly. Thanks.
